name: odoo
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  auto_route:
  bloc:
  flutter_bloc:
  get_it:
  injectable:
  json_annotation:
  freezed_annotation:
  hydrated_bloc:
  path_provider:
  equatable:
  dartz:
  flutter_screenutil:
  chopper:
  intl:

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  auto_route_generator:
  build_runner:
  freezed:
  injectable_generator:
  json_serializable:
  flutter_lints: ^2.0.0
  chopper_generator:

flutter:
  uses-material-design: true
